# Introduktion

Denne hjemmeside har til formål at klæde personale på som indsamler data i LIVING forskningsprojektet. Nogle procedure kan opdateres undervejs, hvis løbende kommer på bedre metoder. Alle ændringer vil ske på denne hjemmeside, hvorfor det er vigtigt at man orienterer sig på denne hjemmeside inden der skal foretages dataindsamling.

For at sikre høj kvalitet i forskningsprojektet LIVING er det afgørende, at dataindsamlingen følger faste procedurer. Dette bidrager til ensartet indsamling af data, uanset hvilken medarbejder der foretager målinger og tests. Ud over at levere pålidelige data til forskningsprojektet, har manualen også til formål at sikre, at borgerne har en positiv oplevelse af at deltage. Inden borgerne undersøges, skal de underskrive en samtykkeerklæring, der giver Steno Diabetes Center Aarhus til at anvende resultaterne til forskningsformål. 

Det vurderes at testprocedurerne tager ca. 45 min.

**Kontakt vedr. dataindsamling:**

Jonas Munk Jensen, Projektmedarbejder

[Jonas.munk.jensen\@rm.dk](mailto:Jonas.munk.jensen@rm.dk){.email}

Tlf: 24607984

## Procedurer

**@sec-afklarende-samtale** en beskrivelse af  
