# Samtykkeerklæring {#sec-samtykkeerklæring}

**Informeret samtykke til deltagelse i et sundhedsvidenskabeligt forskningsprojekt**

Forskningsprojektets titel: LIVING – fysisk aktivitet i et kommunalt uddannelsestilbud til borgere med type 2-diabetes.

**Erklæring fra deltager i forskningsprojektet:**

Jeg har fået skriftlig og mundtlig information, og jeg ved nok om formål, metode, fordele og ulemper til at sige ja til at deltage. Jeg ved, at det er frivilligt at deltage, og at jeg altid kan trække mit samtykke tilbage uden at miste mine nuværende eller fremtidige rettigheder til behandling. Jeg giver samtykke til, at deltage i forskningsprojektet, og har fået en kopi af dette samtykkeark samt en kopi af den skriftlige information om projektet til eget brug.

Navn på deltager i forskningsprojektet: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

Dato: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

Underskrift: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

Ønsker du at blive informeret om forskningsprojektets resultat samt eventuelle konsekvenser for dig?:

Ja \_\_\_\_\_\_ (sæt x) Nej \_\_\_\_\_\_ (sæt x)

**Erklæring fra den, der afgiver information:**

Jeg erklærer, at deltageren i forskningsprojektet har modtaget mundtlig og skriftlig information om undersøgelsen. Efter min overbevisning er der givet tilstrækkelig information til, at der kan træffes beslutning om deltagelse i undersøgelsen.

Navnet på den, der har afgivet information: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

Dato: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

Underskrift: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
