project:
  type: website

website:
  page-navigation: true
  title: "LIVING forskningsprojekt"
  site-url: "https://jonasmunkjensen.github.io/LIVING/"
  repo-url: "https://jonasmunkjensen.github.io/LIVING/"

  author: "Jonas Munk Jensen"
  date: 2024 07 31
  date-format: "YYYY"

  page-footer:
    right: "Denne hjemmeside er lavet i [Quarto](https://quarto.org/)."

  sidebar:
    background: "#D9E3E4"
    logo: figures/rmlogo.PNG
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/Jonasmunkjensen/LIVING
        text: "LIVING"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Forside
      - href: 0-introduktion.qmd
        text: Introduktion
      - href: afklarende-samtale.qmd
        text: 2-testmanual.qmd
      - href: 3-REDCap.qmd
        text: REDCap
      - href: 4-opsætning-af-aktivitetsmåler.qmd
        text: Klargøring af aktivitetsmålere
      - href: 5-HbA1c-apparat.qmd
        text: Procedurer for HbA1c apparat
      - href: 6-Samtykkeerklæring.qmd
        text: Samtykkeerklæringer til print
      - href: 7-udstyrsliste.qmd
      - text: 7-udstyrsliste.qmd

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true

filters:
  - include-files.lua
  - quarto


