project:
  type: website

website:
  title: "LIVING forskningsprojekt"
  site-url: "https://jonasmunkjensen.github.io/LIVING/"
  repo-url: "https://jonasmunkjensen.github.io/LIVING/"
  page-navigation: true
  search: true

  page-footer:
    right: "Denne hjemmeside er lavet i [Quarto](https://quarto.org/)."

  navbar:
    background: light
    logo: logo.PNG
    logo-alt: Steno Diabetes Center Aarhus
    title: false
    tools:
      - icon: github
        href: https://github.com/Jonasmunkjensen/LIVING
        text: "LIVING"
    collapse-below: lg
    left:
      - text: "Forside"
        href: index.qmd
      - text: "Introduktion"
        href: 0-introduktion.qmd
      - text: "Afklarende samtale"
        href: 1-afklarende-samtale.qmd
      - text: "Testmanual"
        href: 2-testmanual.qmd
      - text: "REDCap"
        href: 3-REDCap.qmd
      - text: "Aktivitetsmålere"
        href: 4-opsætning-af-aktivitetsmåler.qmd
      - text: "HbA1c apparat"
        href: 5-HbA1c-apparat.qmd
      - text: "Samtykkeerklæringer"
        href: 6-Samtykkeerklæring.qmd
      - text: "Udstyrsliste"
        href: 7-udstyrsliste.qmd

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    toc: true
