project:
  type: book
  output-dir: docs


book:
  title: "LIVING forskningsprojekt"
  author: "Jonas Munk Jensen"
  date: 2024 07 31
  date-format: "YYYY"
  chapters:
    - index.qmd
    - 0-introduktion.qmd
    - 1-afklarende-samtale.qmd
    - 2-testmanual.qmd
    - 3-REDCap.qmd
    - 4-opsætning-af-aktivitetsmåler.qmd
    - 5-HbA1c-apparat.qmd
cookie-consent:
  type: express
  palette: light
google-analytics:
  tracking-id: "G-98HE1VGDR4"

execute:
  freeze: auto
  echo: false # change to false to hide code

format:
  html:
    theme: cosmo
    default-image-extension: svg
